// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubzvbhubngtldpmfvbxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVienZiaHVibmd0bGRwbWZ2Ynh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTY5MDksImV4cCI6MjA1ODY3MjkwOX0.FWgxW9orPZFgVX__JCVBIe91JMrsq89PkNO6YcygycA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);